config/routes.rb
Rails.application.routes.draw do
  resources :articles

  # Defines the root path route ("/")
  root to: "pages#home"

  # Routes definition
  get "home", to: "pages#home"
  get "about", to: "pages#about"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :description, presence: true, length: { maximum: 50 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # Visualização de todos os artigos
  def index
    @articles = Article.all.reverse
  end

  # Visualização de um artigo
  def show
  end

  # Visualização da página de criação
  def new
    @article = Article.new
  end

  # Visualização da página de edição de artigo
  def edit
  end

  # Action de criação do artigo
  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article # Redirecionamento para o show do artigo
    else
      render "new", status: :unprocessable_entity # Erro de processamento
    end
  end

  # Action de atualização de artigo
  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render "edit", status: :unprocessable_entity # Erro de processamento
    end
  end

  # Deleta o registro de um artigo
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_br_datetime(date)
    date.strftime("%d/%m/%Y %H:%M")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_card.html.erb
<div class="col col-sm-6 col-md-4 my-3">
    <div class="card text-center">
    <div class="card-header">
        Created By Vinícius Toshio
    </div>
    <div class="card-body">
        <h5 class="card-title"><%= article.title %></h5>
        <p class="card-text"><%= article.description %></p>

        <div class="d-flex justify-content-center gap-2">
            <%= link_to "Read", article, class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-primary" %>
            <%= button_to "Delete", article, method: :delete, data:{turbo_confirm: "Are you sure?"}, form:{ class: "btn btn-outline-danger"}, class: "unstyled-button" %>
        </div>
    </div>
    <div class="card-footer text-body-secondary">
        <small>
            Created at <%= format_br_datetime(article.created_at) %>
        </small> 
        <% unless article.created_at === article.updated_at then %>
            <small>
                - Updated at <%= format_br_datetime(article.updated_at) %>
            </small>
        <% end %>
    </div>
    </div>
</div>

app/views/articles/_form.html.erb
<%= render "shared/errors" %>

<%= form_with(model: @article, local: true) do |form| %>
    <div class="form-group my-2">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group my-2">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group my-2">
        <%= form.label :content, class: "form-label" %>
        <%= form.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group my-4 text-center">
        <%= form.submit "Save Article", class: "btn btn-outline-primary" %>
    </div>
<% end %>

<div class="d-flex justify-content-center">
    <%= link_to "[Cancel and Get Back to Articles]", articles_path %>
</div>

app/views/articles/edit.html.erb
<section class="container my-4">
    <div class="mx-auto w-50">
        <div class="d-flex gap-3 align-items-center mb-4">
            <h1>Edit Article</h1>
        </div>
        <%= render "articles/form" %>
    </div>
</section>

app/views/articles/index.html.erb
<section class="container my-4">
    <div class="d-flex gap-3 align-items-center mb-4">
        <h1 class="fw-bold">Articles</h1>
        <%= link_to "Publish New Article", new_article_path, class: "btn btn-outline-success" %>
    </div>

    <% unless @articles.empty? then %>
        <div class="row">
        <% @articles.each do |article| %>
                <%= render partial: "articles/card", locals: {article: article} %>
        <% end%>
        </div>
    <% else %>
        <p>There's no articles here :(</p>
    <% end%>
</section>

app/views/articles/new.html.erb
<section class="container my-4">
    <div class="mx-auto w-50">
        <div class="d-flex gap-3 align-items-center mb-4">
            <h1>Create new Article</h1>
        </div>
        <%= render "articles/form" %>
    </div>
</section>

app/views/articles/show.html.erb
<section class="m-3 w-100">
    <div class="btn-group">
        <%= link_to "<i class='bi bi-box-arrow-left'></i>".html_safe, articles_path, class: "btn btn-outline-primary"%>
        <%= link_to "<i class='bi bi-pencil'></i>".html_safe, edit_article_path(@article), class: "btn btn-outline-secondary" %>
        <%= button_to "<i class='bi bi-trash'></i>".html_safe, article_path(@article), method: :delete, data: { turbo_confirm: "Are you sure?" }, form: { class: "btn btn-outline-danger" }, class: "unstyled-button" %>
    </div>
</section>
<section class="container">
    <div class="d-block">
        <h1><%= @article.title %></h1>
        <p><%= format_br_datetime(@article.created_at) %> - <%= @article.description %></p>
    </div>
    <div class="">
        <p><%= @article.content %></p>
    </div>

</section>

app/views/layouts/_footer.html.erb
<footer class="sticky-footer" data-bs-theme="dark">
    <div class="container">
        <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <span class="mb-3 mb-md-0 text-body-secondary">© 2025 Company, Inc</span>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class=" alert alert-success alert-dismissable fade show m-3" role="alert">
        <%= msg %>
        <button class="close btn btn-outline-success" type="button" data-bs-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>    
<% end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "My Blog", home_path, class: "navbar-brand logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", home_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bootstrap Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module", defer: true %>
  </head>

  <body class="d-flex flex-column min-vh-100" data-bs-theme="dark">
    <header>
      <%= render "layouts/navigation" %>
    </header>
    <main class="flex-shrink-0 min-vh-100">
      <%= render "layouts/messages" %>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<p>This is the about page!</p>

app/views/pages/home.html.erb
<div class="container py-5" data-bs-theme="dark">
    <div class="p-5 mb-4 rounded-3 home-jumbotron">
        <div class="container-fluid py-5 text-center text-light">
            <h1 class="display-5 fw-bold">Home Page</h1>
            <p class="fs-4">
                Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
            </p>
            <hr class="my-4">
            <%= link_to "Sign up!", home_path, class: "btn btn-success px-3 fs-4" %>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
    <div class="alert alert-danger text-muted">
        <h3>The following errors prevented the article from being saved:</h2>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end%>
        </ul>
    </div>
<% end %>